name: Build
on:
  push:
    branches: [main]
    paths:
      - 'svg/**'
      - 'icons.json'
      - 'templates/**'
      - 'sass/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerate fonts, CSS, and docs"
          file_pattern: "font/* css/* sass/_vars.scss docs/* composed/*"
